version: "2.1"

networks:
  webapp:

services:
  static:
    image: sigoden/dufs
    ports:
      - 5000:5000
    volumes:
      - "./files:/data"
    command: "/data -A -a /@${USERNAME}:${PASSWORD}"

  music:
    image: phanan/koel
    container_name: music
    depends_on:
      - database
    ports:
      - 3000:80
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=${MUSIC_DB_HOST}
      - DB_USERNAME=${USERNAME}
      - DB_PASSWORD=${PASSWORD}
      - DB_DATABASE=${MUSIC_DB_NAME}
      - FORCE_HTTPS=${MUSIC_FORCE_HTTPS}
    volumes:
      - ./files/music:/music
      - ./files/covers:/var/www/html/public/img/covers
      - ./files/search-indexes:/var/www/html/storage/search-indexes
    networks:
      - webapp

  database:
    image: mysql/mysql-server:5.7
    ports:
      - 3036:3036
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${PASSWORD}
      - MYSQL_DATABASE=${MUSIC_DB_NAME}
      - MYSQL_USER=${USERNAME}
      - MYSQL_PASSWORD=${PASSWORD}
    networks:
      - webapp

  web:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/ssl
    ports:
      - "443:443"
    depends_on:
      - static
      - music
      - database